[modules.e2e]
source = ".dagger/modules/e2e"
# The git repository to run tests against as an end-to-end smoke test.
# settings.repo = ""

[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[sdks.dang]
module = "dagger-dang-sdk"

[sdks.dang.scopes."."]
is-module = true
name = "vitest"
